services:
  mysql:
    build: .
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root123!"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "app123!"
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
